name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  NODE_VERSION: ${{ vars.NODE_VERSION }}

jobs:
  lint:
    name: 🪥 Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: ${{ env.NODE_VERSION }}
          cache-dependency-path: "**/yarn.lock"
      - name: Install dependencies
        run: yarn install
      - name: Checking lint
        run: |
          yarn lint

  testing:
    name: 👔 Test & Coverage
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/setup-node@v3
        with:
          cache: "yarn"
          node-version: ${{ env.NODE_VERSION }}
          cache-dependency-path: "**/yarn.lock"
      - name: Install dependencies
        run: yarn install
      - name: Testing
        run: yarn run test
      - name: Coverage check
        uses: devmasx/coverage-check-action@v1.2.0
        with:
          type: lcov
          min_coverage: 100
          result_path: coverage/lcov.info
          token: ${{ github.token }}
